openapi: "3.0.3"
info:
  title: "STD24071"
  description: "This is a specification of STD24071"
  version: "1.0.0"

servers:
  - url: "http://localhost:8000"

paths:
  /health:
    get:
      summary: "Vérifie la santé de l'API"
      responses:
        "200":
          description: "Retourne Ok"
          content:
            text/plain:
              schema:
                type: string
                example: "Ok"

  /phones:
    post:
      summary: "Crée un nouveau téléphone"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Phone"
      responses:
        "201":
          description: "Téléphone créé"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Phone"

    get:
      summary: "Récupère la liste des téléphones"
      responses:
        "200":
          description: "Liste des téléphones"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Phone"

  /phones/{id}:
    get:
      summary: "Récupère un téléphone spécifique"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "Téléphone trouvé"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Phone"
        "404":
          description: "Téléphone non trouvé"
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "Phone avec l'id X n'existe pas ou n'a pas été trouvé."

  /phones/{id}/characteristics:
    put:
      summary: "Met à jour les caractéristiques d’un téléphone"
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CharacteristicUpdate"
      responses:
        "200":
          description: "Caractéristiques mises à jour"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Phone"
        "404":
          description: "Téléphone non trouvé"
          content:
            application/json:
              schema:
                type: object
                properties:
                  detail:
                    type: string
                    example: "Phone avec l'id X n'existe pas ou n'a pas été trouvé."

components:
  schemas:
    Characteristic:
      type: object
      properties:
        ram_memory:
          type: integer
          example: 8
        rom_memory:
          type: integer
          example: 128
      required:
        - ram_memory
        - rom_memory

    Phone:
      type: object
      properties:
        id:
          type: int
          example: 1
        brand:
          type: string
          example: "Samsung"
        model:
          type: string
          example: "Galaxy S23"
        characteristics:
          $ref: "#/components/schemas/Characteristic"
      required:
        - id
        - brand
        - model
        - characteristics


    CharacteristicUpdate:
      allOf:
        - $ref: "#/components/schemas/Characteristic"
